# Generated by Django 4.2.4 on 2023-09-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('current_class', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
